---
# delete a machine for testing Cuckoo automated install
- name: "Delete Cuckoo test machine"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: EC2 Facts
    ec2_instance_facts:
      region: "{{aws_region}}"
      filters:
        tag:Name: "aws-cuckoo"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
    register: ec2
  - name: Delete Cuckoo EC2 instance
    ec2:
      region: "{{aws_region}}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      instance_id: '{{item.instance_id}}'
      state: absent
    with_items: "{{ec2.instances}}"
  - name: Delete Cuckoo security group
    ec2_group:
      region: "{{aws_region}}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      name: "Ansible-Cuckoo"
      state: absent
